<a href="https://colab.research.google.com/github/Setiawansyah/Pengenalan-Pola/blob/main/Matrix_Setiawansyah.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# mengubah dari 1D menjadi matrik 2D 
import numpy as np
a = np.arange(1,21,1)
c = a.reshape((4,5))
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
